% Compute persistence spectrum

% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 12-Apr-2019 17:00:52

% Parameters
timeLimits = [0.55 0.95]; % seconds
frequencyLimits = [0 22050]; % Hz
overlapPercent = 50;

%%
% Index into signal time region of interest
Pos1_ROI = Pos1(:);
timeValues = a;
minIdx = timeValues >= timeLimits(1);
maxIdx = timeValues <= timeLimits(2);
Pos1_ROI = Pos1_ROI(minIdx&maxIdx);
timeValues = timeValues(minIdx&maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[P,F,PWR] = pspectrum(Pos1_ROI,timeValues, ...
    'persistence', ...
    'FrequencyLimits',frequencyLimits, ...
    'OverlapPercent',overlapPercent);
