% Compute persistence spectrum

% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 12-Apr-2019 17:01:17

% Parameters
timeLimits = [0.52 0.92]; % seconds
frequencyLimits = [0 22050]; % Hz
overlapPercent = 50;

%%
% Index into signal time region of interest
Pos3_ROI = Pos3(:);
timeValues = a;
minIdx = timeValues >= timeLimits(1);
maxIdx = timeValues <= timeLimits(2);
Pos3_ROI = Pos3_ROI(minIdx&maxIdx);
timeValues = timeValues(minIdx&maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[P,F,PWR] = pspectrum(Pos3_ROI,timeValues, ...
    'persistence', ...
    'FrequencyLimits',frequencyLimits, ...
    'OverlapPercent',overlapPercent);
