% Compute persistence spectrum

% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 12-Apr-2019 12:29:28

% Parameters
timeLimits = [2.267574e-05 1.337212]; % seconds
frequencyLimits = [0 22050]; % Hz
overlapPercent = 50;

%%
% Index into signal time region of interest
x3_ROI = x3(:);
timeValues = a;
minIdx = timeValues >= timeLimits(1);
maxIdx = timeValues <= timeLimits(2);
x3_ROI = x3_ROI(minIdx&maxIdx);
timeValues = timeValues(minIdx&maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[P,F,PWR] = pspectrum(x3_ROI,timeValues, ...
    'persistence', ...
    'FrequencyLimits',frequencyLimits, ...
    'OverlapPercent',overlapPercent);
