% Compute persistence spectrum

% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 12-Apr-2019 10:14:03

% Parameters
timeLimits = [0.59 0.79]; % seconds
frequencyLimits = [0 22050]; % Hz
overlapPercent = 50;

%%
% Index into signal time region of interest
x50_ROI = x50(:);
timeValues = x0(:,2);
minIdx = timeValues >= timeLimits(1);
maxIdx = timeValues <= timeLimits(2);
x50_ROI = x50_ROI(minIdx&maxIdx);
timeValues = timeValues(minIdx&maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[P,F,PWR] = pspectrum(x50_ROI,timeValues, ...
    'persistence', ...
    'FrequencyLimits',frequencyLimits, ...
    'OverlapPercent',overlapPercent);
